### ISSUE TITLE
我发现安装了插件之后，这2个地方的下来菜单弹不出来了（见图）

### ISSUE THREAD

**Issue by zhouhao** [4074/leetcode-helper#2]
多谢提供这么好的插件。

目前我只能先disable插件，需要的时候再启用。
![image](https://user-images.githubusercontent.com/2281521/45858437-5f9a6f00-bd2b-11e8-93a6-37c617e45269.png)

**Comment by 4074** [comment]
感谢提交 issues，已修复，Google webstore 预计在1小时后生效。
Bootstrap 冲突引起的问题，主要用于显示 tooltips，已替换成 hint.css 的方案。
[Leetcode](https://leetcode.com/) 答题页面更新了UI，刷题更方便了，该版本也做了适配。

**Comment by zhouhao** [comment]
为什么好多人都看到新的UI，我却一直找不到入口，我的UI还是旧的，尴尬！
多谢fix
