### ISSUE TITLE
Not working with LeetCode New UI

### ISSUE THREAD

**Issue by anishkumar127** [4074/leetcode-helper#20]
it's not working anymore with leetcode new ui changes. please fix it. its very useful.

**Comment by 4074** [comment]
@anishkumar127 Sorry for the late. It works for me，can u show a bad case including the url and screenshots.

**Comment by anishkumar127** [comment]
![image](https://user-images.githubusercontent.com/77631750/202620159-34e197c3-b043-476d-bc53-316a99b635b9.png)

**URL QUESTION** _ but its not working any of question _
_previous ui it was working but after ui change in leetcode not working in my side._
https://leetcode.com/problems/two-sum/

**Comment by 4074** [comment]
Aha, I got it. The new UI is only available to some users, not including me. I am trying to get the new UI.

**Comment by anishkumar127** [comment]
Yes slowly slowly they are rolling out to everyone.
u can get new ui i think from new account of leetcode.
