### ISSUE TITLE
"Copy for markdown" button is not working.

### ISSUE THREAD

**Issue by nanpuhaha** [4074/leetcode-helper#22]
"Copied!" alert pops up, but the copy didn't work.

**Comment by williejohn** [comment]
hgfdfghj

**Comment by williejohn** [comment]
@williejohn hi

**Comment by williejohn** [comment]
![github-macros-countallthethings](https://user-images.githubusercontent.com/10358078/155168814-0a4f7c9c-b7e8-4d0c-8f0b-b07c899efc23.jpeg)

**Comment by williejohn** [comment]
chnvhn mbnmnb fxgjfhhjfhjhh

**Comment by williejohn** [comment]
srgjhjcghkmvgjkcnvnmvmbn,cghjxfgjxfmgjkfhghjdshsdzfjzxgdjnzdgjnxfgfmnxfgnxcgnxn

**Comment by 4074** [comment]
Fixed on v1.2.0
