### ISSUE TITLE
0.2.0更新以后反而没有显示copy markdown了

### ISSUE THREAD

**Issue by kniost** [4074/leetcode-helper#3]
貌似新的UI不是每个人都有的，至少我的界面还是旧版~

**Comment by zfu1316** [comment]
那个markdown的button没有了

**Comment by zhouhao** [comment]
有没有人知道怎么去往新版UI？哈哈

**Comment by 4074** [comment]
@kniost @Allen-Zfu @zhouhao 
能看到这个按钮吗？
![1](https://user-images.githubusercontent.com/4033831/45988128-db881480-c0a7-11e8-903a-582bfa1671ef.png)

**Comment by 4074** [comment]
[https://leetcode.com/profile/lab/](https://leetcode.com/profile/lab/) 看下这里，有没 Opt-in for further beta testing 选项

**Comment by zhouhao** [comment]
![image](https://user-images.githubusercontent.com/2281521/45989686-8a3d3e00-c031-11e8-8501-cb05a3dd9713.png)
我也没看到`Opt-in for further beta testing`， T_T

**Comment by 4074** [comment]
@kniost @Allen-Zfu @zhouhao 
已兼容旧版UI
