### ISSUE TITLE
Leetcode 新版本UI的支持

### ISSUE THREAD

**Issue by shuowpro** [4074/leetcode-helper#4]
你好，感谢您的精彩的作品，我非常喜欢这个插件。

我发现这个插件没有办法支持新版本的Leetcode的UI。希望您可以更新支持一下，谢谢。

**Comment by 4074** [comment]
你好，感谢喜欢及反馈。
已支持新的UI。

**Comment by shuowpro** [comment]
非常感谢您的及时回复。
我尝试过重新安装插件，但是只有旧版本的UI才可以成功复制题目，而新版本的UI没有任何反应。

**Comment by 4074** [comment]
最新版本是 0.2.2，我可以更新了。插件更新可能会延迟的，稍后再试试吧。
