### ISSUE TITLE
Description里的Example没有被copy

### ISSUE THREAD

**Issue by mactanxin** [4074/leetcode-helper#5]
测试链接(新版): https://leetcode.com/problems/x-of-a-kind-in-a-deck-of-cards/
**Example** 这一行有, 但是下面具体的内容没有

**Comment by mactanxin** [comment]
更正一下: 是被copy到了 **Note** 下, 所以 **Example**下显示为空

**Comment by 4074** [comment]
Thanks for yours issue. I am sorry to fix it so late.
Happy Chinese New year!!!
