### ISSUE TITLE
可以加入一些自定义的内容吗，比如标题的层级之类

### ISSUE THREAD

**Issue by kniost** [4074/leetcode-helper#6]
现在标题是h3，solution是h4，但是每个笔记软件显示的都有不同，可以自定义是最好的

**Comment by 4074** [comment]
It's a good point. Maybe I have no time to do it this month.
Completely welcome for pull request, if you wanna show your code.

**Comment by YaochengTong** [comment]
@kniost Made [PR](https://github.com/4074/leetcode-helper/pull/15) for changing titles, you can take a lot of my code and modify extension by yourself

**Comment by 4074** [comment]
Now, the title will trans to H1.
